---
collections:
  - "community.general"
  - "ansible.netcommon"
  - "ansible.posix"
  - "ansible.utils"
  - "community.mysql"
  - "community.crypto"
  - "community.docker"
  - "community.vmware"
  - "community.windows"
  - "kubernetes.core"
  - "junipernetworks.junos"
  - "microsoft.ad"
  - "vmware.vmware"
  - "vmware.alb"
  - "vmware.vmware_rest"
  - "containers.podman"
  - "cisco.ios"
  - "cisco.iosxr"
  - "cisco.ise"
